dist: trusty
sudo: false
language: php

cache:
  directories:
    - node_modules
    - vendor
    - wordpress
    #only for sonarcloud
    - "$HOME/.sonar/cache"

env:
  global:
    # SONAR_GITHUB_TOKEN encrypted
    secure: CziVGOOe4LRSP0qbTN/JeSGr8UFXTgheQ/TLC/DqGSMrzP8i0manNpA3fXXYG8QxxravsEBWh8zs0UmDBL9mBfpDzIGkDEZ6JBvBUF4RPZ9kAsV/dWoCjhJpa6HPAi62Srj+caCwFqHbmoez2AwRwYeVi95+od/J6rIhqzf92roVcObTP1zfFsaY+Pse1jCo9HshtvhJuCnKzMsiE7lBuQtAEwGmBZNwvltKnsMrGYbE+NEzYIXjkf1GxUa3bsR6vmBkQ44euoMlwJYljbCe5l7XC+rGhlnNcHxu94ofKKwNB1usdEyvC6s5cBB0iHlxyS8XArk5Ad2dVVz9EX1C+NDrGHp10OLuMLvXqI47v09IZ09IcQ36gvChBgf5gPXeU0HkiXK3AjaxN47RGOBwnhVqtlp3tPgcyDUKS6fCvMk1VTP5nAx7VCoT3RrpnrLHogOTHestPiG10IkUCZ9N+tIhSru5eawBGIPUd5Lg1z5UjxsUqAMeNE5FG8k/U/v/NlbzSOBuRhel0U2vfy/0bij9AXJEwLliKiCSQgsENY+5jhP6bBw8SaK25wePcCH+bxSlqKYGvUkq01sNiY6kn/28WKB8er03qwps9zbAMCoYYvQTc5mDG7LUFAdpUs2EFJqSREzqKcvi8N89TUzVSuCdIWRNlYQRzkVK5J9bO+4=

# Declare versions of PHP to use. Use one decimal max.
# @link http://docs.travis-ci.com/user/build-configuration/
matrix:
  # If some rows in the build matrix are allowed to fail, the build won’t be marked as finished until they have completed.
  # mark the build as finished as soon as possible
  fast_finish: true

  include:
    # aliased to a recent 5.6.x version
    - php: '5.6'
      # Declare which versions of WordPress to test against.
      # Also declare whether or not to test in Multisite.
      # lint, other checks and deploy on php5.6
      env: PHPLINT=1 SNIFF=1 WP_VERSION=master WP_MULTISITE=0 DEPLOY=1

    # aliased to a recent 7.x version
    - php: '7.0'
      # only lint on php7.0
      env: PHPLINT=1 SNIFF=0

    # aliased to a java 8 version
    - jdk: oraclejdk8
      # only sonarqube tests
      env: SONAR_QUBE=1
      #only for sonoarQube
      addons:
        sonarcloud:
          organization: betterworld
        token:
          secure: BK9nGQEWraiE0eKiB2aDgpj511GpoYV4oMMuoGgnTqDt63clOzC1/VsLjEmNiSJKinKwr/IqYK+qiBWiBzkDLN6FVqVlnx0UAn5OotzpAiybgcVMMYs7lIOUPvEG04yrIEFyhvzHOrLxhKikTXLqMXDpPkYmvep/JdJFjfc5b7JJ21OwUVgWVxYS5h6fw71I6SgOuED8AiqgNhRanCUNlB+sc2tv3NcpW9dM3OsaqhtSpcyj4eR/g11XW2jgjb2cEnzwijSvLIfz1rSt9cDPxNgmsxLjviqtLaUBmI5Nl2Pc/HxwfKyBJZsepQCmgtMwZW678O+2NYurOODz10pob4B8bEGQip4K9hOWqcVdYMPLuWxrECu54aImxgkqiyfEDKW6S0klSpVaUCQPtoK4BX7q1OqB7YgHReU/GKCCSeq14vqwSxOhNCx2gmi4W/dQtihrcrOPmOScP0NEnDk4hzh270XemjGxCfoHM2bhVTVSvm/803Jm084BdXF1IMEQOusXeaixqw8FWvr301bEvaGfMSjbt/OR2mPSUabtQIU6knCpl3Qb3Wk9VdTfiE/kEQy7KLSnn5q0OPfb2/sNsvJ11FHW86cp2tDTgpMWABxEceR3NsSWRDstsV9W0PEsfGhpIWubEDGgIQIN0EgXCyIYhAQNnESaoh1SWnZq8Pw=
        branches:
          - master

before_install:
  - nvm install stable
  - npm update -g npm
  - node --version
  - npm --version

install:
  #sonar plugins
  - if [[ $SONAR_QUBE == 1 ]]; then curl https://sonarsource.bintray.com/Distribution/sonar-php-plugin/sonar-php-plugin-2.10.0.2087.jar; fi
  - if [[ $SONAR_QUBE == 1 ]]; then curl https://sonarsource.bintray.com/Distribution/sonar-javascript-plugin/sonar-javascript-plugin-3.1.1.5128.jar; fi
  - if [[ $SONAR_QUBE == 1 ]]; then curl https://github.com/racodond/sonar-css-plugin/releases/download/4.9/sonar-css-plugin-4.9.jar; fi

before_script:
  - chmod +x ./travis_scripts/*.sh
  - "./travis_scripts/before-script.sh"

script:
  - "./travis_scripts/check-code.sh"

#only if $DEPLOY=1
after_success: "./travis_scripts/deploy.sh"

# TODO for the moment the deploy will be triggered when build php5.6 finishes without waiting for sonarCloud build to finish
# see beta feature https://docs.travis-ci.com/user/build-stages
deploy:
  - provider: releases
    api_key:
      secure: KopI0QHd/M5IbgE8a6DUHT+YDGytGMEB28r68mx8BV3dAim09UNaxnABiIk5mWaheC7yUlbQ1LS20uOM9+9Xssa5NyMDiMzN14VjH+ykdkqJvuqGGdLn4eMi7WDljH2J8MfBlsfCIgNGE2ZjeuYf1CTWXaGPOWWRDvKixeMqa0LUP8cLeuh/8UKDAqEXf959/gTkNJI5rqhPGXrrp+Yt+XtsTYJCbW7b7Ue/jWPWfzxaqFKTw1OIckOErIyfBoiMPkozHPTUvdCm+asvkNptgOemjEuw4NFV0TOwqEoU08E23MQ/ZCI+YYHlhxaJe9qSrmHN/hS4v3LQhQL/bbMGuzeKnhs7Vvd0m3ZPKwEkCwz15VHb2JzE5eHeCR5iybK9rXqRcEp+64uYtYjH5veW4DQynXaWFl0pG1uyPlOBEs7dHisDlawQECm0cBboCZtK2lJzmrOr/7aaoB8Fm0j6+LB3lDl8KJWh4v8DKZut5P81XPgloT/clwkXE3Ta8tDdeR9jhVDOQn4nw3hJTYEG4lJ9WgfarA8YDGX6XuZN53sdDc8nrgk5awP0uKpxIj6QT1nHgBS3hNe+RdVYx+hBPkX1zcajzwAPHV5LwLAxcG5rEAlBTdq4LuZwrOOClAs5QjJITXk3gdK5olNwHVNGC7z44e7tT7ctqylOvDG40Rw=
    file_glob: true
    file: "/tmp/better-world-quotes-widget.zip*"
    skip_cleanup: true
    on:
      tags: true
      repo: meilleur-monde/wp-quotes-widget
      condition: "$TRAVIS_PULL_REQUEST = false"

notifications:
  email: false
