# Travis CI (MIT License) configuration file
# @link https://travis-ci.org/

# Use new container based environment
sudo: false

cache:
  directories:
    - node_modules
    - vendor

#use Trusty linux version
dist: precise

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Declare versions of PHP to use. Use one decimal max.
# @link http://docs.travis-ci.com/user/build-configuration/
matrix:
    fast_finish: true

    include:
        # aliased to a recent 5.6.x version
        - php: '5.6'
          # Declare which versions of WordPress to test against.
          # Also declare whether or not to test in Multisite.
          env: SNIFF=1 WP_VERSION=master WP_MULTISITE=0
        # recommended php version for WordPress: 7
        # aliased to a recent 7.x version
        - php: '7.0'

before_install:
  # upgrade npm to 5, 6, or higher
  - nvm install stable
  - npm update -g npm # if necessary
  - node --version
  - npm --version

# Use this to prepare your build for testing.
# e.g. copy database configurations, environment variables, etc.
# Failures in this section will result in build status 'errored'.
before_script:
  # Set up WordPress installation.
  - export WP_DEVELOP_DIR=/tmp/wordpress/
  - mkdir -p $WP_DEVELOP_DIR
  # Use the Git mirror of WordPress.
  - if [[ "$SNIFF" == "1" ]]; then git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR; fi
  #install
  - if [[ "$SNIFF" == "1" ]]; then composer install; fi
  # After CodeSniffer install you should refresh your path.
  - if [[ "$SNIFF" == "1" ]]; then phpenv rehash; fi
  # Install ESLINT: JavaScript Code Style checker
  # @link https://eslint.org/
  - if [[ "$SNIFF" == "1" ]]; then npm install --only=dev; fi
  #keep sure that deploy.sh is executable
  - chmod +x deploy.sh

# Run test script commands.
# Default is specific to project language.
# All commands must exit with code 0 on success. Anything else is considered failure.
script:
  # Search for PHP syntax errors.
  - if [[ "$SNIFF" == "1" ]]; then npm run phplint --silent; fi
  # Run the code through eslint
  - if [[ "$SNIFF" == "1" ]]; then npm run eslint --silent; fi
  # Run the code through stylelint checker
  - if [[ "$SNIFF" == "1" ]]; then npm run stylelint --silent; fi
  # WordPress Coding Standards
      # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
      # @link http://pear.php.net/package/PHP_CodeSniffer/
      # -p flag: Show progress of the run.
      # -s flag: Show sniff codes in all reports.
      # -v flag: Print verbose output.
      # -n flag: Do not print warnings (shortcut for --warning-severity=0)
      # --standard: Use WordPress as the standard.
      # --extensions: Only sniff PHP files.
  - if [[ "$SNIFF" == "1" ]]; then npm run phpcs --silent; fi

# when we create a Tag on master branch, it will generate a zip file with only the files necessary for the plugin
deploy:
  - provider: releases
    script:
      # not executed for pull request
      - ./deploy.sh
    api_key:
      # Github personal access token encrypted using the command 'travis encrypt myAccessTokenString'
      secure: "KopI0QHd/M5IbgE8a6DUHT+YDGytGMEB28r68mx8BV3dAim09UNaxnABiIk5mWaheC7yUlbQ1LS20uOM9+9Xssa5NyMDiMzN14VjH+ykdkqJvuqGGdLn4eMi7WDljH2J8MfBlsfCIgNGE2ZjeuYf1CTWXaGPOWWRDvKixeMqa0LUP8cLeuh/8UKDAqEXf959/gTkNJI5rqhPGXrrp+Yt+XtsTYJCbW7b7Ue/jWPWfzxaqFKTw1OIckOErIyfBoiMPkozHPTUvdCm+asvkNptgOemjEuw4NFV0TOwqEoU08E23MQ/ZCI+YYHlhxaJe9qSrmHN/hS4v3LQhQL/bbMGuzeKnhs7Vvd0m3ZPKwEkCwz15VHb2JzE5eHeCR5iybK9rXqRcEp+64uYtYjH5veW4DQynXaWFl0pG1uyPlOBEs7dHisDlawQECm0cBboCZtK2lJzmrOr/7aaoB8Fm0j6+LB3lDl8KJWh4v8DKZut5P81XPgloT/clwkXE3Ta8tDdeR9jhVDOQn4nw3hJTYEG4lJ9WgfarA8YDGX6XuZN53sdDc8nrgk5awP0uKpxIj6QT1nHgBS3hNe+RdVYx+hBPkX1zcajzwAPHV5LwLAxcG5rEAlBTdq4LuZwrOOClAs5QjJITXk3gdK5olNwHVNGC7z44e7tT7ctqylOvDG40Rw="
    file: "/tmp/better-world-quotes-widget.zip"
    file: "/tmp/better-world-quotes-widget.zip.sha1"
    skip_cleanup: true
    on:
      tags: true
      repo: meilleur-monde/wp-quotes-widget
      condition: "$TRAVIS_PULL_REQUEST = false"

notifications:
  email: false
