dist: trusty
sudo: false
language: php

cache:
  directories:
    - node_modules
    - vendor
    - wordpress
    #only for sonarcloud
    - "$HOME/.sonar/cache"

env:
  global:
    # SONAR_GITHUB_TOKEN encrypted
    secure: CziVGOOe4LRSP0qbTN/JeSGr8UFXTgheQ/TLC/DqGSMrzP8i0manNpA3fXXYG8QxxravsEBWh8zs0UmDBL9mBfpDzIGkDEZ6JBvBUF4RPZ9kAsV/dWoCjhJpa6HPAi62Srj+caCwFqHbmoez2AwRwYeVi95+od/J6rIhqzf92roVcObTP1zfFsaY+Pse1jCo9HshtvhJuCnKzMsiE7lBuQtAEwGmBZNwvltKnsMrGYbE+NEzYIXjkf1GxUa3bsR6vmBkQ44euoMlwJYljbCe5l7XC+rGhlnNcHxu94ofKKwNB1usdEyvC6s5cBB0iHlxyS8XArk5Ad2dVVz9EX1C+NDrGHp10OLuMLvXqI47v09IZ09IcQ36gvChBgf5gPXeU0HkiXK3AjaxN47RGOBwnhVqtlp3tPgcyDUKS6fCvMk1VTP5nAx7VCoT3RrpnrLHogOTHestPiG10IkUCZ9N+tIhSru5eawBGIPUd5Lg1z5UjxsUqAMeNE5FG8k/U/v/NlbzSOBuRhel0U2vfy/0bij9AXJEwLliKiCSQgsENY+5jhP6bBw8SaK25wePcCH+bxSlqKYGvUkq01sNiY6kn/28WKB8er03qwps9zbAMCoYYvQTc5mDG7LUFAdpUs2EFJqSREzqKcvi8N89TUzVSuCdIWRNlYQRzkVK5J9bO+4=

# Declare versions of PHP to use. Use one decimal max.
# @link http://docs.travis-ci.com/user/build-configuration/
matrix:
  # If some rows in the build matrix are allowed to fail, the build won’t be marked as finished until they have completed.
  # mark the build as finished as soon as possible
  fast_finish: true

  include:
    # aliased to a recent 5.6.x version
    - php: '5.6'
      # Declare which versions of WordPress to test against.
      # Also declare whether or not to test in Multisite.
      # lint, other checks and deploy on php5.6
      env: PHPLINT=1 SNIFF=1 WP_VERSION=master WP_MULTISITE=0 DEPLOY=1

    # aliased to a recent 7.x version
    - php: '7.0'
      # only lint on php7.0
      env: PHPLINT=1 SNIFF=0

    # aliased to a java 8 version
    - jdk: oraclejdk8
      # only sonarqube tests
      env: SONAR_QUBE=1
      #only for sonoarQube
      addons:
        sonarcloud:
          organization: betterworld
        token:
          secure: hGX4Bq09e5/fUdedv7HtfYNIOIkl6rd8psqRZEZ5oeK7QbgelwWOrkeuD3BcHI4g781rQ5pFZdUvaZNsnPeTMaCEDCPoLs7vfeQn3EILDbdrBjYUwPHEnbrZxoZRYfJoYG771tt9PrqjvNCu0axz8DNmApz70IM9/UTKhmKZIdO8llAFOnG8poC5eBD37iWxGxniAN5rzcFxp9SmJqzguzDFcIkEyOE4/tvHTFmxubfyfTKunsfjBz/aIwUf4iWA0cRfYxf7zmtXJdRJgUbbvJQeMun9p6zDXTxCY/dmYK6CrFxPEBqSL6BqXJBmtJP3lAFXDeTKMFIrhVjLIJXc3hrPUJdDN4Snj5CH1pm6X+DzzZlCaOX/1z8dXheytXlPF8ZmN9yqLyO0779NL4wENSb1fO+LOqsyF8JWK4IP9PAL8AnuI7kxIZ9DMQlddqxI+wAsFyKubLODoyL3D5j/fZZGbP8sN8/8kLBZeu1lUMODnT6F0xgCrrNCcjLEGFZSW+Aij9c7Z7VRF8nj+YsZRa1jYwiIQ/njqYmLyLPHLjMLI2c/82uSePMYvHY9CgEWoP1zhUvUiwI4X+aTQXoUBdyldIaP+26hGDAYGs3oPDZUz9cN6csPBl+RUrffbmcjVLDcQlGgVnCXBvRRwqMGVECNA1uQwinmb4VCexwNV+s=
        branches:
          - master

before_install:
  - nvm install stable
  - npm update -g npm
  - node --version
  - npm --version

install:
  - if [[ $SONAR_QUBE == 1 ]]; then curl https://sonarsource.bintray.com/Distribution/sonar-php-plugin/sonar-php-plugin-2.10.0.2087.jar; fi

before_script:
  - chmod +x ./travis_scripts/*.sh
  - "./travis_scripts/before-script.sh"

script:
  - "./travis_scripts/check-code.sh"

#only if $DEPLOY=1
after_success: "./travis_scripts/deploy.sh"

# TODO for the moment the deploy will be triggered when build php5.6 finishes without waiting for sonarCloud build to finish
# see beta feature https://docs.travis-ci.com/user/build-stages
deploy:
  - provider: releases
    api_key:
      secure: KopI0QHd/M5IbgE8a6DUHT+YDGytGMEB28r68mx8BV3dAim09UNaxnABiIk5mWaheC7yUlbQ1LS20uOM9+9Xssa5NyMDiMzN14VjH+ykdkqJvuqGGdLn4eMi7WDljH2J8MfBlsfCIgNGE2ZjeuYf1CTWXaGPOWWRDvKixeMqa0LUP8cLeuh/8UKDAqEXf959/gTkNJI5rqhPGXrrp+Yt+XtsTYJCbW7b7Ue/jWPWfzxaqFKTw1OIckOErIyfBoiMPkozHPTUvdCm+asvkNptgOemjEuw4NFV0TOwqEoU08E23MQ/ZCI+YYHlhxaJe9qSrmHN/hS4v3LQhQL/bbMGuzeKnhs7Vvd0m3ZPKwEkCwz15VHb2JzE5eHeCR5iybK9rXqRcEp+64uYtYjH5veW4DQynXaWFl0pG1uyPlOBEs7dHisDlawQECm0cBboCZtK2lJzmrOr/7aaoB8Fm0j6+LB3lDl8KJWh4v8DKZut5P81XPgloT/clwkXE3Ta8tDdeR9jhVDOQn4nw3hJTYEG4lJ9WgfarA8YDGX6XuZN53sdDc8nrgk5awP0uKpxIj6QT1nHgBS3hNe+RdVYx+hBPkX1zcajzwAPHV5LwLAxcG5rEAlBTdq4LuZwrOOClAs5QjJITXk3gdK5olNwHVNGC7z44e7tT7ctqylOvDG40Rw=
    file_glob: true
    file: "/tmp/better-world-quotes-widget.zip*"
    skip_cleanup: true
    on:
      tags: true
      repo: meilleur-monde/wp-quotes-widget
      condition: "$TRAVIS_PULL_REQUEST = false"

notifications:
  email: false
